# Creación de Base de Datos - Jóvenes a la E

Este notebook implementa la estructura de la base de datos para el proyecto Jóvenes a la E. Se encarga de crear todas las tablas necesarias para almacenar la información del programa.

## Contenido

1. **Conexión a MySQL**
   - Establecimiento de conexión con el servidor MySQL local
   - Credenciales de acceso configuradas

2. **Creación de Base de Datos**
   - Nombre: jovenes_a_la_e
   - Creación condicional para evitar duplicados

3. **Estructura de Tablas**

   ### Tabla: localidad
   - Almacena información de las localidades de Bogotá
   - Campos:
     * localidad_id (PK, Auto-increment)
     * nombre_localidad

   ### Tabla: inst_edu_superior
   - Registro de instituciones educativas superiores
   - Campos:
     * inst_edu_superior_id (PK)
     * nombre_inst_edu_superior

   ### Tabla: programa
   - Información de programas académicos
   - Campos:
     * programa_id (PK, Auto-increment)
     * nombre_programa
     * modalidad
     * inst_edu_superior_id (FK)

   ### Tabla: estudiante
   - Datos demográficos y académicos de estudiantes
   - Campos:
     * estudiante_id (PK, Auto-increment)
     * documento_identidad (UNIQUE)
     * rango_edad
     * genero
     * grupo_etnico
     * victima_conflicto_arm
     * discapacidad
     * grupo_sisben
     * percentil_saber11
     * zona_colegio
     * sector_colegio
     * localidad_id (FK)

   ### Tabla: convocatoria
   - Registro de convocatorias del programa
   - Campos:
     * convocatoria_id (PK)
     * anio
     * semestre

   ### Tabla: participacion
   - Registro de participación de estudiantes
   - Campos:
     * participacion_id (PK, Auto-increment)
     * estudiante_id (FK)
     * convocatoria_id (FK)
     * programa_id (FK)

## Notas Técnicas
- Todas las tablas usan InnoDB como motor de base de datos
- Se implementan restricciones de integridad referencial
- Las eliminaciones en cascada están configuradas para mantener la consistencia de datos

In [3]:
# Importar librerias
import mysql.connector as mysql
from pathlib import Path
import logging
import sys

In [4]:
# Configuración de logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)

# Conectar a la base de datos
database_connection = mysql.connect(
    host ='localhost',
    port = 3306,
    user = 'root',
    password = 'adso00',
)

if database_connection.is_connected():
    logging.info("Conexión exitosa a la base de datos")

2025-06-02 11:31:19,034 - INFO - Conexión exitosa a la base de datos

In [5]:
# Definir el cursor
cursor = database_connection.cursor()

# Crear base de datos y tablas
cursor.execute("CREATE DATABASE IF NOT EXISTS jovenes_a_la_e")
cursor.execute("USE jovenes_a_la_e")

cursor.execute("""
CREATE TABLE localidad (
    localidad_id INT PRIMARY KEY AUTO_INCREMENT,
    nombre_localidad VARCHAR(100) NOT NULL
)
""")

cursor.execute("""
CREATE TABLE inst_edu_superior (
    inst_edu_superior_id INT PRIMARY KEY,
    nombre_inst_edu_superior VARCHAR(100) NOT NULL
)
""")

cursor.execute("""
CREATE TABLE programa (
    programa_id INT PRIMARY KEY AUTO_INCREMENT,
    nombre_programa VARCHAR(100) NOT NULL,
    modalidad VARCHAR(50) NOT NULL,
    inst_edu_superior_id INT NOT NULL,
    FOREIGN KEY (inst_edu_superior_id) REFERENCES inst_edu_superior(inst_edu_superior_id) ON DELETE CASCADE
)
""")

cursor.execute("""
CREATE TABLE estudiante (
    estudiante_id INT PRIMARY KEY AUTO_INCREMENT,
    documento_identidad VARCHAR(20) UNIQUE NOT NULL,
    rango_edad VARCHAR(20) NOT NULL,
    genero VARCHAR(20) NOT NULL,
    grupo_etnico VARCHAR(200) NOT NULL,
    victima_conflicto_arm VARCHAR(10) NOT NULL,
    discapacidad VARCHAR(50) NOT NULL,
    grupo_sisben VARCHAR(100) NOT NULL,
    percentil_saber11 VARCHAR(20) NOT NULL,
    zona_colegio VARCHAR(100) NOT NULL,
    sector_colegio VARCHAR(50) NOT NULL,
    localidad_id INT NOT NULL,
    FOREIGN KEY (localidad_id) REFERENCES localidad(localidad_id) ON DELETE CASCADE
)
""")

cursor.execute("""
CREATE TABLE convocatoria (
    convocatoria_id VARCHAR(5) PRIMARY KEY,
    anio INT NOT NULL,
    semestre INT NOT NULL
)
""")

cursor.execute("""
CREATE TABLE participacion (
    participacion_id INT PRIMARY KEY AUTO_INCREMENT,
    estudiante_id INT NOT NULL,
    convocatoria_id VARCHAR(5) NOT NULL,
    programa_id INT NOT NULL,
    FOREIGN KEY (estudiante_id) REFERENCES estudiante(estudiante_id) ON DELETE CASCADE,
    FOREIGN KEY (convocatoria_id) REFERENCES convocatoria(convocatoria_id) ON DELETE CASCADE,
    FOREIGN KEY (programa_id) REFERENCES programa(programa_id) ON DELETE CASCADE
)
""")

# Confirmar cambios
logging.info("Base de datos y tablas creadas exitosamente.")

# Cerrar cursor y conexión
cursor.close()
database_connection.close()

2025-06-02 11:31:19,293 - INFO - Base de datos y tablas creadas exitosamente.